#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
/* 已确认 MCU 与 LED；其余模块引脚尚未分配，不填写猜测值。 */
#define BOARD_DDS_CLOCK_HZ 25000000UL
#define BOARD_SPI_PINS_ASSIGNED 0
#define BOARD_I2C_PINS_ASSIGNED 0
#define BOARD_INPUT_PINS_ASSIGNED 0
#define BOARD_ANALOG_CONTROL_PINS_ASSIGNED 0
#endif

